name: Debug Pipeline

on:
  push:
    branches: [ debug ]
  workflow_dispatch:

jobs:
  debug-build:
    runs-on: ubuntu-latest
    name: Debug Build Process
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Debug - Show project structure
      run: |
        echo "=== Project Structure ==="
        find . -name "*.xml" -o -name "*.java" | head -20
        echo ""
        echo "=== POM Files ==="
        find . -name "pom.xml" -exec echo "File: {}" \; -exec head -10 {} \;
        
    - name: Debug - Maven version and settings
      run: |
        echo "=== Maven Version ==="
        mvn --version
        echo ""
        echo "=== Java Version ==="
        java -version
        echo ""
        echo "=== Environment ==="
        env | grep -E "(JAVA|MAVEN)" || true
        
    - name: Debug - Maven validate
      run: |
        echo "=== Maven Validate ==="
        mvn validate -B -X | head -50
        
    - name: Debug - Maven compile (common only)
      run: |
        echo "=== Compiling Common Module ==="
        cd common
        mvn compile -B -X
        
    - name: Debug - Maven compile (producer only)
      run: |
        echo "=== Compiling Producer Module ==="
        cd producer
        mvn compile -B -X
        
    - name: Debug - Full Maven build
      run: |
        echo "=== Full Maven Build ==="
        mvn clean compile -B -X | tail -100
        
    - name: Debug - Maven package
      run: |
        echo "=== Maven Package ==="
        mvn clean package -DskipTests -B
        echo ""
        echo "=== Build Artifacts ==="
        find . -name "*.jar" -ls
        
    - name: Debug - Docker build context
      run: |
        echo "=== Docker Build Context ==="
        echo "Current directory:"
        pwd
        echo ""
        echo "Files in current directory:"
        ls -la
        echo ""
        echo "Producer Dockerfile:"
        cat producer/Dockerfile | head -20
        echo ""
        echo "Target directories:"
        find . -name "target" -type d -exec ls -la {} \;
